export const listProduct = [
  {
    price: 15000,
    image: "https://ik.imagekit.io/prbjdtauk2z/Project-premium/2_WqgI21US9.png?updatedAt=1701095602196",
    name: "Pack of Beer (6pcs of heineken)",
    desc: "Heineken lager beer, or known as just Heineken, is one of the pale beers with 5% alcohol. Heineken lager beer, or known as just Heineken, is one of the pale beers with 5% alcohol. Heineken lager beer, or known as just Heineken, is one of the pale beers with 5% alcohol.",
    amount: 6,
  },
  {
    price: 15000,
    image: "https://ik.imagekit.io/prbjdtauk2z/Project-premium/9_Dd5XVWD0LJ.png?updatedAt=1701095604775",
    name: "Pack of Beer (6pcs of heineken)",
    desc: "Heineken lager beer, or known as just Heineken, is one of the pale beers with 5% alcohol.",
    amount: 12,
  },
  {
    price: 15000,
    image: "https://ik.imagekit.io/prbjdtauk2z/Project-premium/6__uRc9UeQ6.png?updatedAt=1701095604436",
    name: "Pack of Beer (6pcs of heineken)",
    desc: "Heineken lager beer, or known as just Heineken, is one of the pale beers with 5% alcohol.",
    amount: 23,
  },
  {
    price: 15000,
    image: "https://ik.imagekit.io/prbjdtauk2z/Project-premium/4_spiekhnV2.png?updatedAt=1701095604582",
    name: "Pack of Beer (6pcs of heineken)",
    desc: "Heineken lager beer, or known as just Heineken, is one of the pale beers with 5% alcohol.",
    amount: 44,
  },
  {
    price: 15000,
    image: "https://ik.imagekit.io/prbjdtauk2z/Project-premium/8__SJM2vLuD.png?updatedAt=1701095604751",
    name: "Pack of Beer (6pcs of heineken)",
    desc: "Heineken lager beer, or known as just Heineken, is one of the pale beers with 5% alcohol.",
    amount: 23,
  },
  {
    price: 15000,
    image: "https://ik.imagekit.io/prbjdtauk2z/Project-premium/7_QLMuZkivw.png?updatedAt=1701095604778",
    name: "Pack of Beer (6pcs of heineken)",
    desc: "Heineken lager beer, or known as just Heineken, is one of the pale beers with 5% alcohol.",
    amount: 62,
  },
  {
    price: 15000,
    image: "https://ik.imagekit.io/prbjdtauk2z/Project-premium/1_W0XcW6VQi_.png?updatedAt=1701095604789",
    name: "Pack of Beer (6pcs of heineken)",
    desc: "Heineken lager beer, or known as just Heineken, is one of the pale beers with 5% alcohol.",
    amount: 36,
  },
  {
    price: 15000,
    image: "https://ik.imagekit.io/prbjdtauk2z/Project-premium/10__4CgQbGAd.png?updatedAt=1701095604844",
    name: "Pack of Beer (6pcs of heineken)",
    desc: "Heineken lager beer, or known as just Heineken, is one of the pale beers with 5% alcohol.",
    amount: 12,
  },
  {
    price: 15000,
    image: "https://ik.imagekit.io/prbjdtauk2z/Project-premium/3_mxa4xebiBa.png?updatedAt=1701095604880",
    name: "Pack of Beer (6pcs of heineken)",
    desc: "Heineken lager beer, or known as just Heineken, is one of the pale beers with 5% alcohol.",
    amount: 61,
  },
  {
    price: 15000,
    image: "https://ik.imagekit.io/prbjdtauk2z/Project-premium/5_55Hi9QrsV.png?updatedAt=1701095604903",
    name: "Pack of Beer (6pcs of heineken)",
    desc: "Heineken lager beer, or known as just Heineken, is one of the pale beers with 5% alcohol.",
    amount: 61,
  },
  {
    price: 15000,
    image: "https://ik.imagekit.io/prbjdtauk2z/Project-premium/17_C9KR2dQy3.png?updatedAt=1701095608592",
    name: "Pack of Beer (6pcs of heineken)",
    desc: "Heineken lager beer, or known as just Heineken, is one of the pale beers with 5% alcohol.",
    amount: 61,
  },
  {
    price: 15000,
    image: "https://ik.imagekit.io/prbjdtauk2z/Project-premium/12_g8xauGSUg.png?updatedAt=1701095612548",
    name: "Pack of Beer (6pcs of heineken)",
    desc: "Heineken lager beer, or known as just Heineken, is one of the pale beers with 5% alcohol.",
    amount: 61,
  },
  {
    price: 15000,
    image: "https://ik.imagekit.io/prbjdtauk2z/Project-premium/13_tQRV-ORBE.png?updatedAt=1701095612675",
    name: "Pack of Beer (6pcs of heineken)",
    desc: "Heineken lager beer, or known as just Heineken, is one of the pale beers with 5% alcohol.",
    amount: 61,
  },
  {
    price: 15000,
    image: "https://ik.imagekit.io/prbjdtauk2z/Project-premium/18_1jSATJIwh.png?updatedAt=1701095613941",
    name: "Pack of Beer (6pcs of heineken)",
    desc: "Heineken lager beer, or known as just Heineken, is one of the pale beers with 5% alcohol.",
    amount: 61,
  },
  {
    price: 15000,
    image: "https://ik.imagekit.io/prbjdtauk2z/Project-premium/15_MeTwj8_r6.png?updatedAt=1701095614053",
    name: "Pack of Beer (6pcs of heineken)",
    desc: "Heineken lager beer, or known as just Heineken, is one of the pale beers with 5% alcohol.",
    amount: 61,
  },
  {
    price: 15000,
    image: "https://ik.imagekit.io/prbjdtauk2z/Project-premium/16_miTGtGueY.png?updatedAt=1701095614106",
    name: "Pack of Beer (6pcs of heineken)",
    desc: "Heineken lager beer, or known as just Heineken, is one of the pale beers with 5% alcohol.",
    amount: 61,
  },
  {
    price: 15000,
    image: "https://ik.imagekit.io/prbjdtauk2z/Project-premium/14_KO-R4gy7B.png?updatedAt=1701095614288",
    name: "Pack of Beer (6pcs of heineken)",
    desc: "Heineken lager beer, or known as just Heineken, is one of the pale beers with 5% alcohol.",
    amount: 61,
  },
  {
    price: 15000,
    image: "https://ik.imagekit.io/prbjdtauk2z/Project-premium/20_PC0awjw8c.png?updatedAt=1701095614398",
    name: "Pack of Beer (6pcs of heineken)",
    desc: "Heineken lager beer, or known as just Heineken, is one of the pale beers with 5% alcohol.",
    amount: 61,
  },
  {
    price: 15000,
    image: "https://ik.imagekit.io/prbjdtauk2z/Project-premium/19_RPNn_KiLL4.png?updatedAt=1701095614527",
    name: "Pack of Beer (6pcs of heineken)",
    desc: "Heineken lager beer, or known as just Heineken, is one of the pale beers with 5% alcohol.",
    amount: 61,
  },
  {
    price: 15000,
    image: "https://ik.imagekit.io/prbjdtauk2z/Project-premium/21_lNYGMJOLPf.png?updatedAt=1701095614575",
    name: "Pack of Beer (6pcs of heineken)",
    desc: "Heineken lager beer, or known as just Heineken, is one of the pale beers with 5% alcohol.",
    amount: 61,
  },
  {
    price: 15000,
    image: "https://ik.imagekit.io/prbjdtauk2z/Project-premium/22_i1iSsudXC.png?updatedAt=1701095615049",
    name: "Pack of Beer (6pcs of heineken)",
    desc: "Heineken lager beer, or known as just Heineken, is one of the pale beers with 5% alcohol.",
    amount: 61,
  },
  {
    price: 15000,
    image: "https://ik.imagekit.io/prbjdtauk2z/Project-premium/23_5ZiUmsBiN.png?updatedAt=1701095616749 ",
    name: "Pack of Beer (6pcs of heineken)",
    desc: "Heineken lager beer, or known as just Heineken, is one of the pale beers with 5% alcohol.",
    amount: 61,
  },
  {
    price: 15000,
    image: "https://ik.imagekit.io/prbjdtauk2z/Project-premium/24_1-ov5vnNc.png?updatedAt=1701095617126",
    name: "Pack of Beer (6pcs of heineken)",
    desc: "Heineken lager beer, or known as just Heineken, is one of the pale beers with 5% alcohol.",
    amount: 61,
  },
];
